---
branches:
  only:
  - master

services: docker

language: python
python: "2.7"

env:
  global:
  - ANSIBLE_VARS: {"slurm_type_of_node":"front","SYSTEMS":[{"class":"system","ec3_max_instances_max":1}]}
  matrix:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: "--privileged"
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: "--privileged"
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  # Pull container.
  - 'docker pull grycap/travis:${distro}'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --hostname slurmserver --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} grycap/travis:${distro} "${init}" > "${container_id}"'

  # install dependencies
  - 'docker exec "$(cat ${container_id})" ansible-galaxy install grycap.ntp grycap.munge grycap.im grycap.ssh'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role installation.
  - 'docker exec --tty "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -e ${ANSIBLE_VARS}'
  - 'docker exec --tty "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -e "slurm_type_of_node=wn IM_NODE_HOSTNAME=wn0"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
